# -*- coding: utf-8 -*-
"""Aula 2 - Lista 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IO6jxaAr-qPWefBBmIczyJdmZjCcWbQs

1)Imprimir todos os números de 100 até 1, usando for.(Y)
"""

for y in range (100, 0, -1):
  print(y)

"""2) Criar um algortimo que leia um número e imprima todos os números ímpares na sequência, usando for.(Y)"""

y = int(input("Digite um número inteiro positivo:"))
print("Números impares após", y, ":")
if y % 2 == 0:
  y += 1
else:
   y += 2
for y in range(y, y + 50, 2):
  print(y, end= " ")

"""3) Entrar com a idade de várias pessoas e imprimir: o número total de pessoas com
menos de 21 anos e o total de pessoas com mais de 50 anos, usando for. (Y)
"""

menor_de_21 = 0
maior_de_50 = 0

num_pessoas = int(input("Quantas pessoas você deseja inserir? "))
for y in range(num_pessoas):
    idade = int(input(f"Digite a idade da pessoa {y + 1}: "))
    if idade < 21:
        menor_de_21 += 1
    elif idade > 50:
        maior_de_50 += 1

print(f"Total de pessoas com menos de 21 anos: {menor_de_21}")
print(f"Total de pessoas com mais de 50 anos: {maior_de_50}")

"""4) Criar um algoritmo que imprima a soma dos números pares entre 25 e 200, usando for(Y)"""

soma_pares = 0
for y in range(25, 201):
  if y % 2 == 0:
    soma_pares += y
print("A soma dos números pares entre 25 e 200 é:", soma_pares)

"""5) Criar um algoritmo que imprima os números de 120 a 300, usando for.(Y)"""

for y in range(120, 301):
  print(y)

"""6) Refaça os exercicios acima utilizando while(Y)

6) 1 - Imprimir todos os números de 100 até 1, usando while(Y)
"""

y = (100)
while y>= 1:
  print(y)
  y = y-1

"""6) 2 - Criar um algortimo que leia um número e leia todos os números impares na sequência, usando while(Y)"""

y = int(input("Digite um número inteiro positivo:"))
print("Números impares após", y, ":")
if y % 2 == 0:
  y += 1
else:
   y += 2
contagem = 0
while contagem <50:
  print(y, end=" ")
  y += 2
  contagem += 1

"""6) 3 - Entrar com a idade de várias pessoas e imprimir: o número total de pessoas com menos de 21 anos e o total de pessoas com mais de 50 anos, usando while. (Y)"""

menor_de_21 = 0
maior_de_50 = 0

num_pessoas = int(input("Quantas pessoas você deseja inserir? "))
y = 0

while y < num_pessoas:
    idade = int(input(f"Digite a idade da pessoa {y + 1}: "))
    if idade < 21:
        menor_de_21 += 1
    elif idade > 50:
        maior_de_50 += 1
    y += 1

print(f"Total de pessoas com menos de 21 anos: {menor_de_21}")
print(f"Total de pessoas com mais de 50 anos: {maior_de_50}")

"""6) 4 - Criar um algoritmo que imprima a soma dos números pares entre 25 e 200, usando while(Y)"""

y = 25
soma_pares = 0
while y <= 200:
  if y % 2 == 0:
    soma_pares += y
  y += 1
print("A soma dos números pares entre 25 e 200 é:", soma_pares)

"""6) 5 - Criar um algoritmo que imprima os números de 120 a 300, usando while(Y)"""

y = (120)
while y<=300:
  print(y)
  y = y+1